j1y0ungyoon/gym-tivation

firebase.ts, yarn.lock
firebase initial setting #2 
---
---
- firebase.ts를 추가했습니다.
- Initialize Firebase 초기 설정을 했습니다.
by @park74441
=> firebase initial setting

package.json, pages/api/chat.ts, pages/chat/index.tsx, pages/chat/room/[roomNum].tsx, yarn.lock
---
---
- 채팅 소켓 서버를 구현했습니다. (express 로 리팩토링 필요)
- 전체 채팅이 가능해졌습니다.
- dm 기능이 추가됐습니다.
- dm 보내기 버튼 기능이 추가됐습니다.
- 나의 dm리스트를 볼 수 있습니다.
by @GoMyamMii
=> Apply chat, dm

components/Header.tsx, components/SideNav.tsx, pages/_app.tsx, pages/index.tsx, yarn.lock
---
---
- 페이지 이동 기능이 추가됐습니다.
by @GoMyamMii
=> Apply Link to page

pages/api/chat.ts, pages/chat/index.tsx, pages/chat/room/[roomNum].tsx
---
---
- 내 DM창 기능 구현
- 채팅 토글 버튼 추가
- 전체 채팅방 스타일 추가
by @GoMyamMii
=> Apply MyDmList

components/CalendarAdd.tsx, components/CalendarEdit.tsx, components/Follow.tsx, components/Header.tsx, components/LoginState.tsx, components/MyPageCalendar.tsx, components/ProfileEdit.tsx, components/SideNav.tsx, components/SignInModal.tsx, pages/_app.tsx, pages/follow/index.tsx, pages/myPage/index.tsx, pages/signIn/index.tsx, pages/signUp/index.tsx
---
---
- 기존 캘린더 삭제시 캘린더 컴포넌트를 재랜더링 시키는 작업을 없애고 실시간으로 반영되게 수정했습니다.
- 입력, 수정, 삭제 버튼을 삭제하고 엔터시 가능하게 수정했습니다.
---
- 유효성 검사가 항상 작동되는 부분을 입력시 나타내게 수정했습니다.
---
- follow 정보를 follow page에 임시로 만들었습니다.
- 팔로잉 취소를 만들었습니다.
- 기존 단일 아이디만 추가 되면 팔로잉, 팔로워를 다중으로 가능하게 수정했습니다.
---
- _app.tsx에서 onAuthStateChanged를 사용해서 로그인 정보를 받아오게 만들었습니다. (새로고침 이슈 해결)
by @park74441
=> Fix: modify my page calendar, signup, signin, follow

components/DmChat.tsx, pages/api/chat.ts, pages/chat/index.tsx
---
---
- 내 DM 리스트 추가.
- 전체적인 레이아웃 수정
- DM 채팅을 다이나믹 라우트 형식에서 컴포넌트 형식으로 변경 채팅에 프로필 이미지 추가
by @GoMyamMii
=> Apply MyDmLists

components/Like.tsx, pages/boardDetail/[...params].tsx, pages/galleryDetail/[...params].tsx
* 좋아요 버튼 스타일을 변경했습니다.
---
* 변경된 UI로 이용할 수 있습니다.
---
* 변경된 UI로 이용할 수 있습니다.
by@j1y0ungyoon
=> Change UI on board detail page

components/BoardPost.tsx, components/GalleryPost.tsx, pages/index.tsx
---
---
- 메인페이지의 이미지들을 오운완갤러리에서 가져오도록 수정
- cursor:pointer
by @GoMyamMii
=> Connect main to gallery

components/MyPageCalendar.tsx, pages/myPage/[...params].tsx
---
---
- mypage의 useEffect deps에 authSerice를 추가하여 새로고침 에러를 수정했습니다.
by @park74441
=> fix: useEffect deps authService

components/RecruitPost.tsx, components/SearchColleague.tsx, pages/mapBoard/index.tsx
=> UI: fix mapBoard UI

components/CalendarAdd.tsx, components/CalendarEdit.tsx, components/Follow.tsx, components/Header.tsx, components/Like.tsx, components/LoginState.tsx, components/MyPageBoard.tsx, components/MyPageCalendar.tsx, components/MyPageGallery.tsx, components/MyPageLike.tsx, components/ProfileEdit.tsx, components/SearchUser.tsx, pages/board/Post.tsx, pages/gallery/Post.tsx, pages/myPage/[...params].tsx, pages/signUp/index.tsx
---
---
- ui 수정 했습니다.
- 프로필 수정에 닉네임 유효성 검사를 만들었습니다.
- 게시판 및 좋아요 불러오기를 만들었습니다.
- 캘린더 ui를 수정했습니다.
- post, gallery 추가시 lv, lvName이 추가되게 변경하여 MyPage에 불러올 수 있게 했습니다.
- 프로필 수정시 취소 버튼을 만들었습니다.
- lv기능과 lvName을 만들었습니다.
---
* 이메일 중복 검사를 만들었습니다.
* 닉네임 중복 검사를 만들었습니다.
---
by @park74441
=> Feat/ mypage ui modify, board and like bring

components/CommentList.tsx, components/SearchColleague.tsx, components/SideNav.tsx, pages/api/api.ts, pages/mapBoard/WritingRecruitment.tsx, pages/mapBoard/index.tsx, pages/recruitDetail/[...params].tsx, pages/signUp/index.tsx, type.ts
---
---
- 참여하기 버튼을 추가했습니다.
- url로 글쓰기 페이지에 접근하지 못하도록 조치했습니다.
---
- 비로그인 사용자도 사이드 네브바에서 운동 동료 모집 페이지로 이동할 수 있도록 변경했습니다.
- 비로그인 사용자가 글쓰기, 운동 참여 버튼 등의 조작을 하는 것을 못하도록 조치했습니다.
=> Feat: apply participation button

components/MyPageBoard.tsx, firebase.ts, pages/signIn/index.tsx
---
---
- 게시판 ui 수정 했습니다.
- 게시판 불러오기에 댓글과 좋아요를 불러올 수 있게 수정했습니다.
---
- 구글 로그인 시 닉네임과 lv을 추가하게 했습니다.
---
by @park74441
=> Feat/ mypage ui modify, board and like bring 

components/DmChat.tsx, firebase.ts, pages/chat/index.tsx
---
---
- 이제 채팅을 칠 때 스크롤이 최하단으로 자동으로 이동합니다.
- 이제 채팅에 시간이 나타납니다.
- 이제 DM에 채팅로그가 쌓이고, DM에 들어가면 이전 DM로그를 볼 수 있습니다.
by @GoMyamMii
=> Feat : apply chat ver 1.0.0

pages/_app.tsx
---
---
- <Layout> 중복 컴포넌트 부분 삭제했습니다.
---
by @park74441
=> fix: Layout remove

components/MyPageLike.tsx
---
* 마이페이지 게시판 게시물 사진 영역 삭제
by @j1y0ungyoon
=> Mypage like fixed

components/BoardComment.tsx, components/CalendarAdd.tsx, components/CalendarEdit.tsx, components/Comment.tsx, components/Follow.tsx, components/FollowButton.tsx, components/GalleryComment.tsx, components/Header.tsx, components/LoginState.tsx, components/MyPageBoard.tsx, components/MyPageCalendar.tsx, components/MyPageGallery.tsx, components/MyPageLike.tsx, components/MyPageRecruit.tsx, components/ProfileEdit.tsx, components/SearchUser.tsx, pages/_app.tsx, pages/myPage/[...params].tsx, pages/recruitDetail/[...params].tsx, pages/signIn/index.tsx, pages/signUp/index.tsx, types.d.ts
---
---
- mypage 및 전체 컴포넌트 query로 변경
- 유저검색 query로 변경
- 유저검색 특수문자 replace 설정
- 로그인 에러 firebase 메시지 수정
- 로그인 ui수정 
by @park74441
=> Refactor: mypage usequery

components/board/BoardItem.tsx, pages/board/index.tsx
---
---
- 게시판에 들어갈 때 게시물이 바로 렌더링 되지 않는 현상을 고쳤습니다.
- useQuery로 데이터를 이용하여 데이터를 불러온다면 꼭 로딩 처리를 해줍시다.
=> Fix: fix rendering bug in board page

components/DmButton.tsx, components/DmChat.tsx, components/DmListUserName.tsx, pages/chat/index.tsx, recoil/dmData.ts
---
---
- 파이어베이스 에러 해결
- 콘솔 에러 해결
- 안쓰는 코드 삭제
- dmLists 를 상대방의 아이디가 아닌 닉네임이 뜨도록 변경
by @GoMyamMii
=> Fix : fix dm console error, firebase error

pages/index.tsx
---
---
- 슬라이더 ui 수정
by @GoMyamMii
=> Ui : change main img slider ui

components/MainCommentList.tsx, components/board/BoardItem.tsx, components/board/BoardPost.tsx, components/comment/Comment.tsx, components/comment/CommentList.tsx, components/common/globalModal/Loading.tsx, components/gallery/GalleryItem.tsx, components/mypage/ProfileEdit.tsx, pages/_document.tsx, pages/board/Post.tsx, pages/board/index.tsx, pages/boardDetail/[...params].tsx, pages/chat/index.tsx, pages/gallery/Post.tsx, pages/gallery/index.tsx, pages/galleryDetail/[...params].tsx, pages/index.tsx, pages/mapBoard/index.tsx, pages/myPage/[...params].tsx, pages/recruitDetail/[...params].tsx, pages/signUp/index.tsx, styles/theme.ts
---
---
- 전체적인 ui 수정
by @GoMyamMii
=> Ui : change ui

.gitignore, components/DmButton.tsx, components/FollowButton.tsx, components/common/globalModal/LoginRequiredModal.tsx, public/assets/icons/mapBoard/modalImg.svg
=> Hotfix : modify ui

components/DmButton.tsx, components/FollowButton.tsx, firebase.ts, pages/recruitDetail/[...params].tsx
---
---
- 내가 쓴 글에도 dm 메시지 버튼이 보이는 것을 보이지 않도록 수정했습니다.
- 운동 동료 모집 버튼 색깔이 흰 색인 것을 수정했습니다.
=> Refactor: refactor on DM

components/mypage/MyPageLike.tsx
---
---
- mypage 갤러리 get 부분 제목을 타이틀로 변경
by @park74441
=> fix: 갤러리 제목 부분 변경

pages/chat/index.tsx
---
---
- dmLists 가 제대로 뜨지 않는 버그 수정
by @GoMyamMii
=> Fix : fix dmLists

components/Header.tsx, components/SearchUser.tsx, components/mypage/CalendarAdd.tsx, components/mypage/CalendarEdit.tsx, components/mypage/MyPageCalendar.tsx, components/mypage/MyPageGallery.tsx
---
---
- 유저 검색 close 수정 및 버그 해결
by @park74441
=> Fix: mypage 유저 검색 수정

firebase.ts
---
---
- firebase key 변경
by @park74441
=> Fix: fireabase key

firebase.ts
=> Hotfix: release v.1.1.2

components/mypage/MyPageCalendar.tsx, components/mypage/ProfileEdit.tsx, components/mypage/ProfileUpLoad.tsx
---
---
- 캘린더 축소시 글자 밀림 현상으로 인한 min-width값 조절
by @park74441
=> Ui: Calendar min-width

components/Header.tsx, firebase.ts, pages/signUp/index.tsx
---
---
- 회원가입 약관 동의 모두 동의시 버튼 활성화 수정
- 회원가입 약관 동의 모두 체크시 모두 동의하기 버튼 체크 표시
by @park74441
=> fix: 회원가입 약관 동의 수정

firebase.ts, pages/signIn/index.tsx, pages/signUp/index.tsx
---
---
- 회원가입, 로그인 인풋창 ui 수정
- firebase 키 변경
by @park74441
=> Ui: signup, signin ui 

components/mypage/ProfileEdit.tsx, pages/signIn/index.tsx, pages/signUp/index.tsx
---
---
- 회원가입, 로그인 인풋 미입력시 버튼 미활성화
by @park74441
=> Fix: signup, signin button disabled

components/DmButton.tsx, pages/api/api.ts, pages/chat/index.tsx, styles/GlobalStyle.ts
---
---
- pretendard 폰트 적용
- dmButton 에서 width 값과 height 값을 props로 받도록 수정
by @GoMyamMii
=> Ui : font change

components/mypage/LoginState.tsx, pages/api/api.ts
---
---
- 팔로워, 팔로잉 마우스 호버시 확대 효과와 텍스트 클릭시 이동으로 변경
by @park74441
=> Fix: loginstate hover fix

components/mypage/MyPageBoard.tsx, components/mypage/MyPageLike.tsx, types.d.ts
---
---
- 게시판, 좋아요 유저 사진 추가
by @park74441
=> fix: board userprofilephoto add

pages/_document.tsx, pages/api/api.ts, pages/board/Post.tsx, pages/gallery/Post.tsx, pages/galleryDetail/[...params].tsx
---
* 메타태그 추가
* 배포 전 에러 수정
---
by @j1y0ungyoon
=> Add meta tag

components/mypage/MyPageBoard.tsx, components/mypage/MyPageCalendar.tsx, components/mypage/MyPageLike.tsx, components/mypage/MyPageRecruit.tsx, pages/myPage/[...params].tsx
---
---
- 마이페이지 불러오기 ui 조절 및 확대 크기 조절
by @park74441
=> fix: mypage hover fix and profilephoto

components/comment/MainCommentList.tsx, components/layout/Header.tsx, components/layout/SideNav.tsx, pages/_document.tsx, pages/chat/index.tsx, pages/gallery/Post.tsx, pages/galleryDetail/[...params].tsx, pages/index.tsx
=> Refactor: add alt for SEO and Accessibility

components/mypage/ProfileEdit.tsx
---
---
- 마이페이지 헬프 텍스트 간격을 수정했습니다.
by @park74441
=> Fix: help text fix

components/DmButton.tsx, components/chat/DmChat.tsx, pages/chat/index.tsx
---
---
- 채팅에서 유저 검색시 무한 렌더링되는 버그 수정
- DM 이미 있는 방 확인 로직 리팩토링
by @GoMyamMii
=> Fix : fix infinite render

components/layout/Header.tsx, pages/board/Post.tsx, pages/board/index.tsx, pages/gallery/Post.tsx, pages/mapBoard/WritingRecruitment.tsx, pages/myPage/[...params].tsx, pages/signIn/index.tsx
---
---
- 갤러리, 게시판, 참여중 모임 새로고침 시 로그인 문제 임시 해결
by @park74441
=> fix: login state refresh

README.md
=> Docs: modify ReadMe

components/DmButton.tsx, components/FollowButton.tsx, components/board/BoardPost.tsx, components/gallery/GalleryPost.tsx, firebase.ts, next.config.js, pages/board/Post.tsx, pages/chat/index.tsx, pages/galleryDetail/[...params].tsx
---
* 이미지 태그 넥스트에서 제공하는 이미지태그로 리팩토링
by @j1y0ungyoon
=> Refactor: img tag to NEXT/IMAGE

components/mypage/MyPageBoard.tsx, components/mypage/MyPageGallery.tsx, components/mypage/MyPageLike.tsx, components/mypage/MyPageRecruit.tsx, components/mypage/ProfileEdit.tsx
---
---
- 마이페이지 오운완 갤러리, 작성한 글, 참여중 모임, 좋아요 ui 수정
- 헬프 텍스트 z-index 조정
by @park74441
=> Ui: mypage ui changed

components/DmButton.tsx, components/FollowButton.tsx, components/comment/CommentList.tsx, firebase.ts, pages/board/Post.tsx, pages/boardDetail/[...params].tsx, pages/galleryDetail/[...params].tsx, pages/recruitDetail/[...params].tsx
- 오운완 갤러리 상세페이지의 전체적인 레이아웃을 수정했습니다.
- 갤러리 상세페이지의 팔로우, dm버튼 이미지 크기를 축소했습니다.
- 운동 모집 게시판의 상세페이지에 댓글 레이아웃을 수정했습니다.
=> UI: modify UI of Detail Gallery and Recruit Detail

components/layout/Header.tsx, components/layout/SideNav.tsx, styles/theme.ts
- 헤더를 항상 위쪽에 나오도록 수정
- theme 부분 헤더에 맞게 수정
by @GoMyamMii
=> Ui : change ui header

components/mypage/LoginState.tsx, pages/myPage/[...params].tsx
---
---
- 팔로우 모달창 수정
by @park74441
=> ui: follow modal fix
